//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oficina.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class itens_vendidos
    {
        public int itemvendido { get; set; }
        public int venda_idvenda { get; set; }
        public Nullable<int> qtd { get; set; }
        public Nullable<double> preco_venda { get; set; }
        public Nullable<double> desconto { get; set; }
        public string codigo_barras { get; set; }
        public string descricao { get; set; }
    }
}
