//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oficina.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class mecanico
    {
        public int idmecanico { get; set; }
        public int usuario_idusuario { get; set; }
        public string apelido { get; set; }
        public string funcao { get; set; }
    }
}
