//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oficina.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class oficinaEntities : DbContext
    {
        public oficinaEntities()
            : base("name=oficinaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<contato> contato { get; set; }
        public virtual DbSet<endereco> endereco { get; set; }
        public virtual DbSet<estoque> estoque { get; set; }
        public virtual DbSet<fornecedor> fornecedor { get; set; }
        public virtual DbSet<funcionario> funcionario { get; set; }
        public virtual DbSet<itens_vendidos> itens_vendidos { get; set; }
        public virtual DbSet<mecanico> mecanico { get; set; }
        public virtual DbSet<produto> produto { get; set; }
        public virtual DbSet<servico> servico { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<venda> venda { get; set; }
        public virtual DbSet<view_itens_venda> view_itens_venda { get; set; }
        public virtual DbSet<view_user> view_user { get; set; }
        public virtual DbSet<view_venda> view_venda { get; set; }
    }
}
