//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oficina.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        public int idproduto { get; set; }
        public int idfornecedor { get; set; }
        public int estoque_idestoque { get; set; }
        public string estado { get; set; }
        public string descricao { get; set; }
        public string un { get; set; }
        public string descricao_marca { get; set; }
        public string codigo { get; set; }
        public string codigo_barras { get; set; }
        public Nullable<double> valor_custo { get; set; }
        public Nullable<double> margem_avista { get; set; }
        public Nullable<double> valor_avista { get; set; }
        public Nullable<double> margem_prazo { get; set; }
        public Nullable<double> valor_prazo { get; set; }
        public Nullable<double> margem_atacado { get; set; }
        public Nullable<double> valor_atacado { get; set; }
        public Nullable<System.DateTime> ultima_atualizacao { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
    }
}
