//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oficina.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class servico
    {
        public int idservico { get; set; }
        public int mecanico_idmecanico { get; set; }
        public string descricao { get; set; }
        public Nullable<double> valor { get; set; }
        public Nullable<System.DateTime> data_servico { get; set; }
    }
}
