//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oficina.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class venda
    {
        public int idvenda { get; set; }
        public int cliente_idcliente { get; set; }
        public int funcionario_idfuncionario { get; set; }
        public Nullable<double> valor_total_compra { get; set; }
        public Nullable<System.DateTime> data_venda { get; set; }
        public Nullable<double> desconto_total { get; set; }
        public string forma_pagamento { get; set; }
        public string tipo_cliente { get; set; }
    }
}
