//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oficina.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_user
    {
        public int idusuario { get; set; }
        public string nome { get; set; }
        public string cpf { get; set; }
        public string rg { get; set; }
        public string sexo { get; set; }
        public string nascimento { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public string estado { get; set; }
        public int idendereco { get; set; }
        public string logradouro { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string uf { get; set; }
        public string cep { get; set; }
        public string numero { get; set; }
        public int idcontato { get; set; }
        public string numero_telefone { get; set; }
        public string email { get; set; }
    }
}
